name: Package
on:
  push

env:
  BRANCH: 3.4.14

jobs:
  package:
    name: Package zookeeper
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build package
      run: make package
