name: Package
on:
  push

env:
  BRANCH: 3.4.14
  ZK_VERSION: 3.4.14

jobs:
  package:
    name: Package zookeeper
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - run: |
        echo "MAKE_ARGS=BUILD=${GITHUB_RUN_NUMBER} ZOOKEEPER_VERSION=${ZK_VERSION} GITHUB_ENV=${GITHUB_ENV}" >> $GITHUB_ENV

    - name: Build package
      run: make package

    - name: Get tag
      run: make get-tag ${MAKE_ARGS} >> $GITHUB_ENV

    - name: Push tag
      run: |
        git config user.email brandwatch-bot-github@brandwatch.com
        git config user.name BrandwatchBot
        git tag -am "bw-zookeeper-build release: $RELEASE_TAG" $RELEASE_TAG
        git push origin $RELEASE_TAG
    
    - name: Release zookeeper pacakge
      uses: softprops/action-gh-release@v1
      with:
        body: "Release for branch: ${{ env.BRANCH }}."
        tag_name: ${{ env.RELEASE_TAG }}
        files: |
          build/zookeeper-${{ env.ZK_VERSION }}.tar.gz
        repository: BrandwatchLtd/bw-zookeeper-build
        token: ${{ secrets.BWBOT_BRANDWATCHLTD_GITHUB_TOKEN }}
